database:
  implementation: 'sqlite'
  host: 'localhost'
  port: 3306
  database: 'vaultedtags'
  username: 'root'
  password: ''

license: 'XXXX-XXXX-XXXX-XXXX'

no-tag-selected-placeholder: 'None Selected'

apply:
  sound:
    enabled: true
    type: 'entity_player_levelup'
    volume: 1
    pitch: 2

clear:
  sound:
    enabled: true
    type: 'entity_bat_takeoff'
    volume: 1
    pitch: 2

no-tag-selected:
  sound:
    enabled: true
    type: 'entity_bat_takeoff'
    volume: 1
    pitch: 2