database:
  implementation: 'sqlite'
  host: 'localhost'
  port: 3306
  database: 'vaultedtags'
  username: 'root'
  password: ''

apply:
  sound:
    enabled: true
    type: 'level_up'
    volume: 1
    pitch: 2

clear:
  sound:
    enabled: true
    type: 'bat_take_off'
    volume: 1
    pitch: 2